version: '3.7'
services:
  s3:
    image: adobe/s3mock
    restart: always
    environment:
      - initialBuckets=${S3_INITIAL_BUCKETS}
    ports:
      - ${S3_HTTP_PORT:-9090}:9090
      - ${S3_HTTP_PORT:-9191}:9191
    healthcheck:
      test: curl --fail http://localhost:${S3_HTTP_PORT:-9090}/ || exit 1
      timeout: 3s
      retries: 10
#  zookeeper:
#    image: zookeeper:3.5.5
#    ports:
#      - 2181:2181
#  cassandra:
#    image: cassandra:2.2
#    ports:
#      - 9042:9042
#      - 9164:9164
